name: "Repo Gardener"
description: "Scans for inactive branches, opens PRs for review, and assigns branch creators as reviewers to merge or delete branches."
author: "Armin Broubakarian"
runs:
  using: 'node20'
  main: 'dist/index.js'
