name: "Run Repo Pruner"
on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly
  workflow_dispatch:

jobs:
  repo-pruner:
    runs-on: ubuntu-latest
    steps:
      - name: Run Repo Pruner
        uses: arminbro/repo-pruner@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          inactive_days: 30
          base_branch: main
